name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t notion-trakt:amd64 .
          docker save notion-trakt:amd64 > notion-trakt-amd64.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notion-trakt-docker-image
          path: notion-trakt-amd64.tar
